typography_spectrum: 0.16153276152908802
color:
  brandStrength: 0.6333040087483823
  lightness: 0.4575302640441805
  saturation: 0.2513814875856042
  rhythmicContrast: 0.3863075205590576
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
layout_spectrum: 0.92935143224895
name: Luis de Jesus Rodriguez
navigation:
  - name: 'ideas, peguntas y definiciones de la vida.'
    url: www.luisdejesusrodriguez.com
    type: external
title: compartiendo el camino a la luz
description: un dia a la vez
